### PR TITLE
Add option to pass unparsed JSON input through to jq

### LINKED ISSUE #56: Slurp doesn't slurp
It was my assumption that slurping multiple inputs should work the same as in `jq`, but it does not. For example this works:

```
echo '{ "one": 1 }\n{ "two": 2 }' | jq -s .
```
But this fails to parse past the first object:
```
echo '{ "one": 1 }\n{ "two": 2 }' | yq -s .
```
You can workaround using jq as an intermediary to slurp into array, then pass to yq and strip off the extra array:
```
echo '{ "one": 1 }\n{ "two": 2 }' | jq -s . | yq -s .[0]
```

### PR DESCRIPTION
**Pull request by alerque**
This would close #56 using my suggestion of a pass-through option that doesn't parse the input streams at all, hence allowing any JSON that would be valid `jq` input instead of only what can be parsed as if it was YAML>

Note I'm not a python programmer so the implementation may be a bit on the hackish side of things, but I'm willing to fix it if you point me in the direction of something.

### CODE REVIEW

**Comment by alerque** [comment]
Hmm, it seems `-j` is actually a `jq` argument already, so lets not clobber that.

**Comment by alerque** [comment]
Hmmm, this won't work — the code currently makes some assumptions such as that input and output formats are always the same. My patch works only if keeping JSON as the output format, but not if combined with `-y`.

**Comment by alerque** [comment]
Okay I "fixed" the case of output conversion.

```bash
$ echo '{"a":true}{"b":false}' | ./yq -p -s -y .
- a: true
- b: false

$ echo '{"a":true}{"b":false}' | ./yq -p -y .
a: true
---
b: false
```

My fix is only temporary, I think a general reorganization would make the whole thing a lot more flexible. I started to mess with it but I'm out of time. I'll open another issue for that.

**Comment by kislyuk** [comment]
Thanks for the input, but I don't think this is needed.

The solution to the original problem is to pass the multiple JSON files as separate arguments: `yq file1.json file2.json` instead of concatenating them all to stdin.

**Comment by alerque** [comment]
I understand there is a work around, and I can certainly program around this. But I think you're missing the point here. I don't have JSON files. I have a stream coming in from an API. Of course I can write it all out to files (or named pipes or whatever) and funnel them all back in. The issue here is that `jq` handles this case (the whole point of the slurp argument) but by wanting YAML output I am limited to an entirely different (and much more complex) workflow --- when a simple fix here would allow for `yq` to be used in place of `jq` when YAML output is desired.

As it is I'm piping stuff to `jq` just to turn around and send it into `yq` which then passes it back to `jq`. Is _that_ really necessary? Or would a pass through option so `jq` only has to see the data once be better?

**Pull request closed without merging**
